const {createRequire}=require('node:module');
const req=createRequire('C:/Users/AVSok/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');
const {chromium}=req('playwright');const fs=require('node:fs');const path=require('node:path');const sharp=req('sharp');
const out=path.join(__dirname,'evidence');fs.mkdirSync(out,{recursive:true});
const base='http://localhost:8792/artifacts/visual-review/prototype.html';
const screens=['home','lessons','vehicle','calibration','drive','pause','theory','result','editor'];
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[];
for(const [width,height]of[[1280,720],[1920,1080]]){await page.setViewportSize({width,height});for(const id of [...screens,'vr']){await page.goto(base+'#'+id);await page.waitForLoadState('networkidle');await page.screenshot({path:path.join(out,id+'-'+width+'.png'),fullPage:false});const layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,broken:[...document.images].filter(x=>!x.complete||!x.naturalWidth).map(x=>x.src),contentHeight:document.documentElement.scrollHeight,viewportHeight:innerHeight}));checks.push({screen:id,width,height,...layout});}const tiles=[];for(let i=0;i<screens.length;i++){const buf=await sharp(path.join(out,screens[i]+'-'+width+'.png')).resize(640,360).toBuffer();tiles.push({input:buf,left:(i%3)*640,top:Math.floor(i/3)*390});const label=Buffer.from(`<svg width="640" height="30"><rect width="640" height="30" fill="#18232e"/><text x="15" y="21" font-family="Arial" font-size="16" fill="#d0e2ef">${i+1}. ${screens[i]} / ${width} × ${height}</text></svg>`);tiles.push({input:label,left:(i%3)*640,top:Math.floor(i/3)*390+360});}await sharp({create:{width:1920,height:1170,channels:4,background:'#14191e'}}).composite(tiles).png().toFile(path.join(out,'contact-'+width+'.png'));}
await page.setViewportSize({width:1280,height:720});await page.goto(base);await page.getByRole('button',{name:'Выбрать занятие',exact:true}).click();if(!page.url().endsWith('#lessons'))throw Error('Home→lessons');await page.locator('[data-lesson="5"]').click();if(!(await page.locator('h2').textContent()).includes('Въезд в бокс'))throw Error('Lesson selection');await page.getByRole('button',{name:'Условия поездки',exact:true}).click();await page.getByRole('button',{name:'Ночь',exact:true}).click();await page.getByRole('button',{name:'Дождь',exact:true}).click();await page.getByRole('button',{name:'К занятию →',exact:true}).click();if(!(await page.locator('.hud-stage>img').getAttribute('src')).includes('night'))throw Error('Night setting');await page.getByRole('button',{name:'Ⅱ Пауза',exact:true}).click();await page.getByRole('button',{name:'Завершить и посмотреть разбор',exact:true}).click();if(!page.url().endsWith('#result'))throw Error('Pause→result');
await page.goto(base+'#calibration');await page.getByRole('button',{name:'Сохранить демо-профиль',exact:true}).click();await page.screenshot({path:path.join(out,'state-calibration-error.png'),fullPage:true});if(!(await page.locator('#calstatus').textContent()).includes('Ошибка'))throw Error('Missing disconnected error');await page.getByRole('button',{name:'Включить виртуальную калибровку',exact:true}).click();await page.locator('#steer').fill('180');await page.locator('[data-axis="0"]').fill('65');await page.getByRole('button',{name:'Сохранить демо-профиль',exact:true}).click();if(!(await page.locator('#calstatus').textContent()).includes('сохранён'))throw Error('Calibration saving');await page.screenshot({path:path.join(out,'state-calibration-success.png'),fullPage:true});
await page.goto(base+'#theory');await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();if(!(await page.locator('#toast').textContent()).includes('Выберите'))throw Error('Theory empty');await page.locator('[data-answer="1"]').click();await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();await page.screenshot({path:path.join(out,'state-theory-wrong.png'),fullPage:true});if(!(await page.locator('#explanation').textContent()).includes('Попробуйте'))throw Error('Wrong answer');await page.getByRole('button',{name:'Начать заново',exact:true}).click();await page.locator('[data-answer="0"]').click();await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();await page.screenshot({path:path.join(out,'state-theory-correct.png'),fullPage:true});if(!(await page.locator('#explanation').textContent()).includes('Верно'))throw Error('Correct answer');
await page.goto(base+'#editor');await page.waitForLoadState('networkidle');await page.locator('[data-tool="Знак"]').click();await page.locator('#mapSvg').click({position:{x:300,y:200}});if(!(await page.locator('#mapstatus').textContent()).includes('несохранённые'))throw Error('Unsaved state');await page.screenshot({path:path.join(out,'state-editor-dirty.png'),fullPage:true});const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Экспорт JSON ↓',exact:true}).click();const download=await downloadPromise;await download.saveAs(path.join(out,'exported-map-demo.json'));const data=JSON.parse(fs.readFileSync(path.join(out,'exported-map-demo.json'),'utf8'));if(!data.demonstration||data.uiMarkers.length!==1||!data.masterplan)throw Error('Export data');await page.getByRole('button',{name:'↶ Отменить',exact:true}).click();if(await page.locator('#mapSvg>g[transform^="translate("]').count()!==1)throw Error('Undo marker');
await page.goto(base+'#vr');await page.locator('[data-vrlesson="4"]').click();if(!page.url().endsWith('#lessons'))throw Error('VR lesson');
await page.goto(base+'#pause');await page.locator('#fov').fill('90');if((await page.locator('#fovvalue').textContent())!=='90°')throw Error('FOV');await page.getByRole('button',{name:'Применить в прототипе',exact:true}).click();await page.screenshot({path:path.join(out,'state-settings-applied.png'),fullPage:true});
await page.goto(base+'#home');await page.keyboard.press('Tab');await page.screenshot({path:path.join(out,'state-focus.png'),fullPage:false});
fs.writeFileSync(path.join(__dirname,'qa-measurements.json'),JSON.stringify({capturedAt:new Date().toISOString(),checks,errors,interactionTests:'PASS: home→lessons→vehicle→drive→pause→result; lesson choice; night; calibration missing/virtual/save; theory empty/wrong/correct; marker/unsaved/export/undo; VR lesson; FOV/apply'},null,2));await browser.close();console.log(JSON.stringify({checks,errors,interactionTests:'PASS'},null,2));})().catch(e=>{console.error(e);process.exitCode=1});
