using System;
using System.Collections.Generic;
using System.Linq;
using DrivingSchool.Learning;
using DrivingSchool.Presentation;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;

namespace DrivingSchool.Editor
{
    /// <summary>
    /// Autodrome v4: geometry traced from the reference scheme (schema.jpg, 100 x 100 m) with one
    /// exercise of each type. Road surface, markings, cones and sign positions come from
    /// Data/Training/autodrome-schema.json (generated by tools/autodrome_from_schema); this file
    /// places them, builds the ramp and props, and defines the lessons and the exam route.
    /// North is +Z, the plot centre is (0, 0), the plot spans -50..50 m on both axes.
    /// </summary>
    public static partial class TrainingGroundBuilder
    {
        const string SchemaData = Base + "/Data/Training/autodrome-schema.json";
        const string SignFaces = Base + "/Art/TrainingKit/SignFaces/";

        /// <summary>
        /// Scheme metres to world metres. The scheme is drawn as 100 x 100 m; at 1.25 the plot becomes
        /// 125 x 125 m, two-lane roads 7.5 m and exercise corridors about 4.4 m. Everything tied to the
        /// scheme (surfaces, cones, signs, lessons, cameras) scales with it; models keep their real size.
        /// </summary>
        public const float SchemeScale = 1.25f;
        const float K = SchemeScale;
        public const float PlotHalf = 50 * K;

        // Estakada (exercise 3) on the lane south of the central road, driven eastbound.
        // Length scales with the layout; height scales too so the grade stays at about 12 %.
        const float RampZ = 7.6f * K, RampHalfWidth = 1.7f * K, RampHeight = .6f * K;
        const float RampStart = -26.8f * K, RampTopStart = -21.8f * K, RampTopEnd = -18.8f * K, RampEnd = -13.9f * K;

        [Serializable] class SchemaMesh { public float[] v; public int[] t; }
        [Serializable] class SchemaSign { public float x, z, heading; public string[] plates; }
        [Serializable] class SchemaSignal { public float x, z, heading; public float[] pedestrian; }
        [Serializable] class SchemaLayout
        {
            public string source;
            public SchemaMesh road, paint;
            public float[] cones;
            public SchemaSign[] signs;
            public SchemaSignal[] signals;
        }

        static Vector3 P(float x, float z) => new Vector3(x * K, 0, z * K); // scheme metres

        static void BuildConnectedLayout()
        {
            var asset = AssetDatabase.LoadAssetAtPath<TextAsset>(SchemaData);
            if (!asset) throw new System.IO.FileNotFoundException(SchemaData);
            var data = JsonUtility.FromJson<SchemaLayout>(asset.text);

            Box("Landscape", new Vector3(0, -.3f, 0), new Vector3(PlotHalf * 2 + 70, .3f, PlotHalf * 2 + 70), grass, environment, 9);
            var baseSlab = Box("Autodrome Base", new Vector3(0, -.05f, 0), new Vector3(PlotHalf * 2, .1f, PlotHalf * 2), zoneAsphalt, environment, 9);
            SetPlanarUV(baseSlab, PlotHalf * 2, PlotHalf * 2);

            FlatMesh("TG_RoadSurface", data.road, .012f, asphalt, environment, 4f);
            FlatMesh("TG_Markings", data.paint, .022f, white, markings, 1f);

            for (int i = 0; i + 1 < data.cones.Length; i += 2) Cone(data.cones[i] * K, data.cones[i + 1] * K);

            BuildRamp();
            BuildRailwayCrossing();
            foreach (var s in data.signs) PlaceSignStack(s);
            BuildCrossroadSignals(data.signals);
            PaintedWords();
            ServiceFacilities();
        }

        // ---------------------------------------------------------------- surfaces
        static void FlatMesh(string name, SchemaMesh src, float y, Material mat, Transform parent, float uvMetres)
        {
            int n = src.v.Length / 2;
            var vertices = new Vector3[n];
            var uv = new Vector2[n];
            var normals = new Vector3[n];
            for (int i = 0; i < n; i++)
            {
                float x = src.v[i * 2] * K, z = src.v[i * 2 + 1] * K;
                vertices[i] = new Vector3(x, y, z);
                uv[i] = new Vector2(x / uvMetres, z / uvMetres);
                normals[i] = Vector3.up;
            }
            var mesh = new Mesh { name = name, indexFormat = IndexFormat.UInt32 };
            mesh.vertices = vertices; mesh.uv = uv; mesh.normals = normals; mesh.triangles = src.t;
            mesh.RecalculateBounds();
            string path = Base + "/Art/TrainingKit/" + name + ".asset";
            var old = AssetDatabase.LoadAssetAtPath<Mesh>(path);
            if (old) { EditorUtility.CopySerialized(mesh, old); UnityEngine.Object.DestroyImmediate(mesh); mesh = old; }
            else AssetDatabase.CreateAsset(mesh, path);
            var go = new GameObject(name, typeof(MeshFilter), typeof(MeshRenderer));
            go.transform.SetParent(parent);
            go.GetComponent<MeshFilter>().sharedMesh = mesh;
            var r = go.GetComponent<MeshRenderer>();
            r.sharedMaterial = mat; r.shadowCastingMode = ShadowCastingMode.Off;
            go.isStatic = true;
        }

        static void SetPlanarUV(GameObject box, float sx, float sz)
        {
            // A cube's default UVs stretch one texture over the whole face; tile it instead.
            var mf = box.GetComponent<MeshFilter>();
            var m = UnityEngine.Object.Instantiate(mf.sharedMesh);
            var v = m.vertices; var uv = new Vector2[v.Length];
            for (int i = 0; i < v.Length; i++) uv[i] = new Vector2(v[i].x * sx / 4f, v[i].z * sz / 4f);
            m.uv = uv; m.name = box.name + " UV";
            string path = Base + "/Art/TrainingKit/TG_BaseSlab.asset";
            var old = AssetDatabase.LoadAssetAtPath<Mesh>(path);
            if (old) { EditorUtility.CopySerialized(m, old); UnityEngine.Object.DestroyImmediate(m); m = old; }
            else AssetDatabase.CreateAsset(m, path);
            mf.sharedMesh = m;
        }

        // ---------------------------------------------------------------- exercise 3 ramp
        static float RampProfile(float x)
        {
            if (x <= RampStart || x >= RampEnd) return 0;
            if (x < RampTopStart) return RampHeight * (x - RampStart) / (RampTopStart - RampStart);
            if (x <= RampTopEnd) return RampHeight;
            return RampHeight * (RampEnd - x) / (RampEnd - RampTopEnd);
        }

        static float Height(float x, float z) => Mathf.Abs(z - RampZ) <= RampHalfWidth ? RampProfile(x) : 0;

        static void BuildRamp()
        {
            var xs = new[] { RampStart, RampTopStart, RampTopEnd, RampEnd };
            var verts = new List<Vector3>(); var tris = new List<int>();
            float z0 = RampZ - RampHalfWidth, z1 = RampZ + RampHalfWidth;
            // Top surface (driven, collider on layer 9).
            for (int i = 0; i < xs.Length; i++) { float h = RampProfile(xs[i]) + .001f; verts.Add(new Vector3(xs[i], h, z0)); verts.Add(new Vector3(xs[i], h, z1)); }
            for (int i = 0; i < xs.Length - 1; i++) { int k = i * 2; tris.AddRange(new[] { k, k + 1, k + 2, k + 1, k + 3, k + 2 }); }
            // Side walls.
            foreach (float zz in new[] { z0, z1 })
            {
                int b = verts.Count;
                for (int i = 0; i < xs.Length; i++) { verts.Add(new Vector3(xs[i], 0, zz)); verts.Add(new Vector3(xs[i], RampProfile(xs[i]), zz)); }
                for (int i = 0; i < xs.Length - 1; i++)
                {
                    int k = b + i * 2;
                    if (zz < RampZ) tris.AddRange(new[] { k, k + 1, k + 2, k + 1, k + 3, k + 2 });
                    else tris.AddRange(new[] { k, k + 2, k + 1, k + 1, k + 2, k + 3 });
                }
            }
            var mesh = new Mesh { name = "TG_Estakada" }; mesh.SetVertices(verts); mesh.SetTriangles(tris, 0);
            mesh.RecalculateNormals(); mesh.RecalculateBounds();
            string path = Base + "/Art/TrainingKit/TG_Estakada.asset";
            var old = AssetDatabase.LoadAssetAtPath<Mesh>(path);
            if (old) { EditorUtility.CopySerialized(mesh, old); UnityEngine.Object.DestroyImmediate(mesh); mesh = old; }
            else AssetDatabase.CreateAsset(mesh, path);
            var go = new GameObject("У3 / Estakada ramp", typeof(MeshFilter), typeof(MeshRenderer));
            go.transform.SetParent(environment);
            go.GetComponent<MeshFilter>().sharedMesh = mesh;
            go.GetComponent<MeshRenderer>().sharedMaterial = concrete;
            go.layer = 9; go.isStatic = true;
            go.AddComponent<MeshCollider>().sharedMesh = mesh;

            // Yellow safety edges along both sides and painted lines across the top.
            for (int i = 0; i < xs.Length - 1; i++)
            {
                float xa = xs[i], xb = xs[i + 1], ha = RampProfile(xa), hb = RampProfile(xb);
                var a = new Vector3(xa, ha, 0); var b = new Vector3(xb, hb, 0);
                float len = Vector3.Distance(a, b); float pitch = Mathf.Atan2(hb - ha, xb - xa) * Mathf.Rad2Deg;
                foreach (float zz in new[] { z0 + .12f, z1 - .12f })
                {
                    var edge = Box("Ramp safety edge", new Vector3((xa + xb) / 2, (ha + hb) / 2 + .01f, zz), new Vector3(len, .02f, .24f), yellow, markings);
                    edge.transform.rotation = Quaternion.Euler(0, 0, pitch);
                }
            }
            RampLine(-23.6f * K); // СТОП-1: stop on the ascent
        }

        static void RampLine(float x)
        {
            float h = RampProfile(x), pitch = Mathf.Atan2(RampHeight, RampTopStart - RampStart) * Mathf.Rad2Deg;
            var line = Box("Ramp stop line", new Vector3(x, h + .012f, RampZ), new Vector3(.4f, .015f, RampHalfWidth * 2 - .5f), white, markings);
            line.transform.rotation = Quaternion.Euler(0, 0, pitch);
        }

        // ---------------------------------------------------------------- exercise 9 railway
        static void BuildRailwayCrossing()
        {
            // The crossing kit as built for v3 (track module, signals carrying sign 1.3.1), moved to the
            // scheme's position. Kit prefabs face -Z at yaw 0. The module's deck and ramps span 7.2 m (x)
            // by 9.6 m (z) around its origin; rails run along x for 11 m. The ring is two-way here, so each
            // approach gets its signal on the right-hand side, 3.6 m before the rails.
            const float cx = -45.42f * K, cz = 30.1f * K; // centre of the ring carriageway at the scheme's tracks
            Place(Kit + "TK_RailwayCrossing_Tracks.prefab", new Vector3(cx, 0, cz), 90);
            Place(Kit + "TK_RailwaySignal.prefab", new Vector3(cx + 4.7f, 0, cz - 3.6f), 0);    // northbound approach
            Place(Kit + "TK_RailwaySignal.prefab", new Vector3(cx - 4.7f, 0, cz + 3.6f), 180);  // southbound approach
        }

        // ---------------------------------------------------------------- signs and signals
        static void PlaceSignStack(SchemaSign s)
        {
            // The sign face (+Z of every prefab) turns towards the traffic it governs.
            float yaw = s.heading + 180;
            for (int i = 0; i < s.plates.Length; i++)
            {
                string plate = s.plates[i];
                float drop = i * .78f;
                GameObject go;
                if (plate.StartsWith("tex:", StringComparison.Ordinal)) go = TexturedSign(plate.Substring(4), s.x * K, s.z * K, yaw, drop, i == 0);
                else
                {
                    go = PlaceSign(plate, s.x * K, s.z * K, yaw);
                    if (go) go.transform.position += Vector3.down * drop;
                }
                if (go) go.name = "Sign / " + plate + " / " + s.heading.ToString("0");
            }
        }

        static readonly Dictionary<string, Material> signMaterials = new Dictionary<string, Material>();

        static Material SignMaterial(string face, bool back)
        {
            string key = face + (back ? "/back" : "");
            if (signMaterials.TryGetValue(key, out var cached) && cached) return cached;
            string texPath = SignFaces + face + ".png";
            var importer = (TextureImporter)AssetImporter.GetAtPath(texPath);
            if (importer && (!importer.alphaIsTransparency || importer.wrapMode != TextureWrapMode.Clamp))
            {
                importer.alphaIsTransparency = true; importer.wrapMode = TextureWrapMode.Clamp; importer.mipmapEnabled = true;
                importer.SaveAndReimport();
            }
            var tex = AssetDatabase.LoadAssetAtPath<Texture2D>(texPath);
            var m = Mat("Sign_" + face + (back ? "_Back" : ""), back ? new Color(.55f, .57f, .6f) : Color.white, back ? .35f : .25f, tex);
            m.SetFloat("_AlphaClip", 1); m.SetFloat("_Cutoff", .5f); m.EnableKeyword("_ALPHATEST_ON");
            m.renderQueue = (int)RenderQueue.AlphaTest;
            m.doubleSidedGI = false;
            signMaterials[key] = m;
            return m;
        }

        static GameObject TexturedSign(string face, float x, float z, float yaw, float drop, bool withPost)
        {
            var root = new GameObject("Sign / " + face).transform;
            root.SetParent(props);
            root.SetPositionAndRotation(new Vector3(x, 0, z), Quaternion.Euler(0, yaw, 0));
            bool plate = face.StartsWith("Plate", StringComparison.Ordinal);
            if (withPost)
            {
                var post = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
                post.name = "Post"; post.transform.SetParent(root, false);
                post.transform.localPosition = new Vector3(0, 1.5f, -.03f); post.transform.localScale = new Vector3(.07f, 1.5f, .07f);
                post.GetComponent<Renderer>().sharedMaterial = concrete;
                UnityEngine.Object.DestroyImmediate(post.GetComponent<Collider>());
            }
            float w = plate ? .6f : .7f, h = plate ? .4f : .7f;
            float cy = 2.62f - drop + (plate ? .12f : 0);
            // Unity quads face -Z; turn the face 180 degrees so it looks along +Z.
            var front = GameObject.CreatePrimitive(PrimitiveType.Quad);
            front.name = "Face"; front.transform.SetParent(root, false);
            front.transform.localPosition = new Vector3(0, cy, .005f); front.transform.localRotation = Quaternion.Euler(0, 180, 0);
            front.transform.localScale = new Vector3(w, h, 1);
            front.GetComponent<Renderer>().sharedMaterial = SignMaterial(face, false);
            UnityEngine.Object.DestroyImmediate(front.GetComponent<Collider>());
            var back = GameObject.CreatePrimitive(PrimitiveType.Quad);
            back.name = "Back"; back.transform.SetParent(root, false);
            back.transform.localPosition = new Vector3(0, cy, -.005f);
            back.transform.localScale = new Vector3(-w, h, 1);
            back.GetComponent<Renderer>().sharedMaterial = SignMaterial(face, true);
            UnityEngine.Object.DestroyImmediate(back.GetComponent<Collider>());
            return root.gameObject;
        }

        static void BuildCrossroadSignals(SchemaSignal[] poles)
        {
            var cycle = new GameObject("У8 / Signal cycle").AddComponent<CrossroadSignalCycle>();
            cycle.transform.SetParent(props);
            var ns = new List<TrafficSignalView>(); var ew = new List<TrafficSignalView>();
            var walkNs = new List<TrafficSignalView>(); var walkEw = new List<TrafficSignalView>();
            foreach (var p in poles)
            {
                var v = PlaceSign("DS_Signal_Vehicle", p.x * K, p.z * K, p.heading + 180);
                if (v)
                {
                    v.name = "Signal / vehicle / " + p.heading.ToString("0");
                    var view = v.GetComponentInChildren<TrafficSignalView>();
                    bool northSouth = Mathf.Abs(Mathf.DeltaAngle(p.heading, 0)) < 1 || Mathf.Abs(Mathf.DeltaAngle(p.heading, 180)) < 1;
                    if (view) (northSouth ? ns : ew).Add(view);
                }
                foreach (float face in p.pedestrian)
                {
                    var dir = Quaternion.Euler(0, face, 0) * Vector3.forward;
                    var ped = PlaceSign("DS_Signal_Pedestrian", p.x * K + dir.x * .45f, p.z * K + dir.z * .45f, face);
                    if (!ped) continue;
                    ped.name = "Signal / pedestrian / " + face.ToString("0");
                    var view = ped.GetComponentInChildren<TrafficSignalView>();
                    // A head facing north or south serves a crosswalk over an east-west arm.
                    bool acrossEastWestArm = Mathf.Abs(Mathf.DeltaAngle(face, 0)) < 1 || Mathf.Abs(Mathf.DeltaAngle(face, 180)) < 1;
                    if (view) (acrossEastWestArm ? walkNs : walkEw).Add(view);
                }
            }
            cycle.northSouth = ns.ToArray(); cycle.eastWest = ew.ToArray();
            cycle.walkWithNorthSouth = walkNs.ToArray(); cycle.walkWithEastWest = walkEw.ToArray();
        }

        // ---------------------------------------------------------------- words painted on lanes
        static void PaintedWords()
        {
            GroundWord("СТАРТ", -28.9f * K, RampZ, 90, 0);
            GroundWord("СТОП-1", -24.3f * K, RampZ, 90, RampProfile(-24.3f * K) + .05f);
            GroundWord("СТОП", -8.3f * K, RampZ, 90, 0);
            GroundWord("СТАРТ", 39.1f * K, 34.3f * K, 270, 0);
        }

        static void GroundWord(string text, float x, float z, float readingYaw, float y)
        {
            // Rotated so the word reads across the lane, like the lettering on the scheme.
            Text(text, new Vector3(x, y + .04f, z), 0, .9f, white, markings);
            markings.GetChild(markings.childCount - 1).rotation = Quaternion.Euler(90, readingYaw, 0);
        }

        // ---------------------------------------------------------------- facilities
        static void ServiceFacilities()
        {
            // 3: vehicle parking along the south fence (stall lines are part of the markings mesh).
            ParkedVehicle(P(-42.5f, -47.4f), 180);
            ParkedVehicle(P(-30.5f, -47.4f), 180);
            ParkedVehicle(P(-27.5f, -47.4f), 180);
            PlaceSign("DS_Sign_Parking", -48.6f * K, -44.2f * K, 0);
            // 4: waiting shelter, 6: information stand, 7: portable toilet.
            Place(Kit + "TK_InstructorShelter.prefab", P(44.5f, -44.5f), 0);
            Billboard(33.8f * K, -48.6f * K, 180);
            var wc = Box("7 / Portable toilet", new Vector3(48.6f * K, 1.15f, -38.3f * K), new Vector3(1.2f, 2.3f, 1.2f), teal, props, 10);
            if (!wc.GetComponent<Collider>()) wc.AddComponent<BoxCollider>();

            // Fence of 5 m panels on the plot boundary, with an 8 m gate in the south side.
            float gateX = 28 * K, h = PlotHalf;
            Place(Kit + "TK_Gate_8m.prefab", new Vector3(gateX, 0, -h));
            int panels = Mathf.RoundToInt(h * 2 / 5);
            float step = h * 2 / panels;
            for (int i = 0; i < panels; i++)
            {
                float t = -h + step * (i + .5f);
                Place(Kit + "TK_Fence_5m.prefab", new Vector3(t, 0, h));
                if (Mathf.Abs(t - gateX) >= 4 + step / 2) Place(Kit + "TK_Fence_5m.prefab", new Vector3(t, 0, -h));
                Place(Kit + "TK_Fence_5m.prefab", new Vector3(-h, 0, t), 90);
                Place(Kit + "TK_Fence_5m.prefab", new Vector3(h, 0, t), 90);
            }
            foreach (var p in new[] { P(-38, 36), P(28, 26), P(-30, -18), P(30, -19), P(5, 30), P(-6, 24) })
                Place(Kit + "TK_Lamp_7m.prefab", p);
            for (float x = -45; x <= 45; x += 15) { float a = x * K, b = PlotHalf + 6; Tree(a, b); Tree(a, -b); Tree(b, a); Tree(-b, a); }
        }

        static GameObject LocalBox(string name, Vector3 local, Vector3 size, Material mat, Transform parent)
        {
            var b = Box(name, Vector3.zero, size, mat, parent);
            b.transform.localPosition = local; b.transform.localRotation = Quaternion.identity;
            return b;
        }

        static void Billboard(float x, float z, float yaw)
        {
            var root = new GameObject("6 / Information stand").transform;
            root.SetParent(props);
            root.SetPositionAndRotation(new Vector3(x, 0, z), Quaternion.Euler(0, yaw, 0));
            LocalBox("Post L", new Vector3(-2.2f, 1.6f, 0), new Vector3(.12f, 3.2f, .12f), asphalt, root);
            LocalBox("Post R", new Vector3(2.2f, 1.6f, 0), new Vector3(.12f, 3.2f, .12f), asphalt, root);
            LocalBox("Board", new Vector3(0, 2.3f, 0), new Vector3(4.8f, 1.8f, .08f), white, root);
            LocalBox("Header", new Vector3(0, 3.0f, -.05f), new Vector3(4.6f, .35f, .02f), teal, root);
            // TextMesh is read looking along its +Z, so the lettering sits on the board's -Z face.
            Text("ОБЯЗАННОСТИ ПЕШЕХОДА И ВОДИТЕЛЯ НА АВТОДРОМЕ", Vector3.zero, 0, .15f, white, root);
            var header = root.GetChild(root.childCount - 1); header.localPosition = new Vector3(0, 3.0f, -.07f); header.localRotation = Quaternion.identity;
            Text("1. Скорость не более 20 км/ч\n2. Пристегните ремень безопасности\n3. Остановка у знака СТОП и стоп-линии\n4. Уступите дорогу пешеходам на переходе\n5. Выполняйте указания инструктора",
                Vector3.zero, 0, .14f, asphalt, root);
            var body = root.GetChild(root.childCount - 1); body.localPosition = new Vector3(0, 2.15f, -.06f); body.localRotation = Quaternion.identity;
        }

        static void Tree(float x, float z, float scale = 1.0f)
        {
            var tree = new GameObject("Tree").transform;
            tree.SetParent(environment);
            tree.position = new Vector3(x, 0, z);
            var trunk = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
            trunk.name = "Trunk"; trunk.transform.SetParent(tree);
            trunk.transform.localPosition = new Vector3(0, 1.8f * scale, 0);
            trunk.transform.localScale = new Vector3(.35f * scale, 1.8f * scale, .35f * scale);
            trunk.GetComponent<Renderer>().sharedMaterial = trunkMat;
            UnityEngine.Object.DestroyImmediate(trunk.GetComponent<Collider>());
            foreach (var (y, s) in new[] { (3.5f, 2.8f), (4.6f, 2.2f) })
            {
                var f = GameObject.CreatePrimitive(PrimitiveType.Sphere);
                f.name = "Foliage"; f.transform.SetParent(tree);
                f.transform.localPosition = new Vector3(0, y * scale, 0);
                f.transform.localScale = new Vector3(s * scale, s * .85f * scale, s * scale);
                f.GetComponent<Renderer>().sharedMaterial = leafMat;
                UnityEngine.Object.DestroyImmediate(f.GetComponent<Collider>());
            }
        }

        static GameObject PlaceSign(string name, float x, float z, float yaw = 0)
        {
            string prefabPath = Base + "/Prefabs/Traffic/" + name + ".prefab";
            var asset = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);
            if (!asset) asset = AssetDatabase.LoadAssetAtPath<GameObject>(Base + "/Art/Traffic/" + name + ".fbx");
            if (!asset) { Debug.LogWarning("Missing sign model " + name); return null; }
            var go = (GameObject)PrefabUtility.InstantiatePrefab(asset, props);
            go.transform.SetPositionAndRotation(new Vector3(x, 0, z), Quaternion.Euler(0, yaw, 0));
            go.layer = 0;
            foreach (var c in go.GetComponentsInChildren<Collider>()) c.gameObject.layer = 0;
            sources.Add(prefabPath);
            return go;
        }

        static void DoubleSidedZoneBoard(int number, Vector3 pos, float yaw)
        {
            Place(Kit + "TK_ZoneBoard.prefab", pos, yaw);
            string numStr = number.ToString("00");
            var fwd = Quaternion.Euler(0, yaw, 0) * Vector3.forward;
            Text(numStr, pos + new Vector3(0, 2.2f, 0) + fwd * .08f, yaw, .75f, white, props);
            Text(numStr, pos + new Vector3(0, 2.2f, 0) - fwd * .08f, yaw + 180, .75f, white, props);
        }

        // Exercise boards stand beside each exercise, off the carriageway; index follows the lesson list.
        static void AddLessonBoard(int i, CourseLesson l)
        {
            var boards = new Dictionary<string, (int number, Vector3 at)>
            {
                ["crossing"] = (2, P(-5, -26.6f)),
                ["boxpark"] = (6, P(-8.6f, -14)),
                ["hill"] = (3, P(-33, 4.4f)),
                ["junction"] = (8, P(5.5f, 18.5f)),
                ["parallel"] = (7, P(26.5f, 40.6f)),
                ["slalom"] = (5, P(36.5f, -5)),
                ["shiftbrake"] = (10, P(-8, 40.4f)),
                ["railway"] = (9, P(-37.5f, 21.5f)),
                ["90turns"] = (4, P(-26, 22)),
            };
            if (boards.TryGetValue(l.id, out var b)) DoubleSidedZoneBoard(b.number, b.at, 0);
        }

        // ---------------------------------------------------------------- lessons and exam route
        // Lanes (right-hand traffic, 3 m each): south ring westbound z -30.5 / eastbound z -33.5;
        // west ring northbound x -43.9 / southbound x -47; north road eastbound z 44 / westbound z 47
        // (the westbound lane is exercise 10); east ring southbound x 44; N-S road northbound x 17.8 /
        // southbound x 14.8; central road eastbound z 10.5 / westbound z 13.5; ramp lane z 7.6.
        public static TrainingCourse CreateCourse() => ScaleCourse(SchemeCourse());

        /// <summary>Lessons are authored in scheme metres; positions and lane-sized gates scale with the
        /// layout. Stop frames that must hold the whole car keep their size (they are sized to the car).</summary>
        static TrainingCourse ScaleCourse(TrainingCourse c)
        {
            c.halfWidth *= K; c.halfLength *= K;
            foreach (var l in c.lessons)
            {
                l.startX *= K; l.startZ *= K;
                foreach (var list in new[] { l.gates, l.transfer })
                    if (list != null)
                        foreach (var g in list)
                        {
                            g.x *= K; g.z *= K;
                            if (!g.wholeVehicle) { g.width *= K; g.length *= K; }
                        }
            }
            return c;
        }

        static TrainingCourse SchemeCourse()
        {
            var none = new CourseGate[0];
            const float RampZ = 7.6f; // scheme metres inside this table
            return new TrainingCourse
            {
                id = "schema-single-100m-v4", halfWidth = 50, halfLength = 50, examTime = 1500, speedLimitKph = 30,
                lessons = new[]
                {
                    L("start", "Старт", "Троньтесь с места и остановитесь в рамке на 2 секунды.", 17.8f, -38.3f, 0,
                        new[] { G("Начало движения", 17.8f, -37.6f, 0, 5, 4, direction: 1), G("Остановка", 17.8f, -35.6f, 0, 4.5f, 7, 2, whole: true, tolerance: 12) },
                        new[] { G("Налево на кольцо", 10, -30.5f, 270, 6, 6, direction: 1) }),
                    L("crossing", "У2 · Пешеходный переход", "Остановитесь перед переходом, затем проезжайте.", 10, -30.5f, 270,
                        new[] { G("Остановка перед переходом", 5.8f, -30.5f, 270, 4.5f, 6, 2, whole: true), G("Проезд перехода", -4, -30.5f, 270, 5, 6, direction: 1) },
                        new[] { G("К боксу", -9, -30.5f, 270, 6, 5, direction: 1) }),
                    L("boxpark", "У6 · Въезд в бокс", "Поверните направо в коридор, проедьте за стоп-линию, въедьте в бокс задним ходом. Выезд направо.", -8, -30.5f, 270,
                        new[] { G("Въезд в коридор", -15, -25.5f, 0, 7, 5, direction: 1), G("За стоп-линию", -15, -17.5f, 0, 7, 8, direction: 1),
                                G("Бокс задним ходом", -21.9f, -17.4f, 90, 3.3f, 5.6f, 2, -1, true, tolerance: 10), G("Выезд из бокса", -15, -21, 180, 7, 6, direction: 1) },
                        new[] { G("Направо на кольцо", -20, -30.5f, 270, 6, 6, direction: 1), G("Западное кольцо на север", -43.9f, -5, 0, 6, 8, direction: 1) }),
                    L("hill", "У3 · Эстакада", "Направо на полосу эстакады. Остановитесь у линии СТОП-1 на подъёме, троньтесь без отката, остановитесь у линии СТОП.", -34, RampZ, 90,
                        new[] { G("Подъезд к эстакаде", -30.5f, RampZ, 90, 3.6f, 4, direction: 1), G("Остановка на подъёме (СТОП-1)", -25.6f, RampZ, 90, 3.6f, 6, 2, whole: true, tolerance: 12),
                                G("Спуск", -16, RampZ, 90, 3.6f, 4, direction: 1), G("Остановка у линии СТОП", -10.6f, RampZ, 90, 3.6f, 5.8f, 2, whole: true, tolerance: 15) },
                        new[] { G("К перекрёстку", 2, 10.5f, 90, 6, 6, direction: 1) }),
                    L("junction", "У8 · Регулируемый перекрёсток", "Остановитесь перед стоп-линией, затем поверните налево (на север). Фазы светофора пока не оцениваются.", 0, 10.5f, 90,
                        new[] { G("Перед стоп-линией", 3.6f, 10.5f, 90, 4.5f, 5.6f, 2, whole: true), G("Левый поворот", 17.8f, 25, 0, 5, 6, direction: 1) },
                        new[] { G("Прямо до северной дороги", 17.8f, 37.5f, 0, 6, 6, direction: 1), G("Направо по северной дороге", 32, 44, 90, 6, 8, direction: 1),
                                G("Восточное кольцо на юг", 44, 40, 180, 6, 5, direction: 1) }),
                    L("parallel", "У7 · Параллельная парковка", "Направо в полосу. Проедьте место, припаркуйтесь задним ходом, выезжайте направо (на север).", 44, 40, 180,
                        new[] { G("Въезд в полосу", 39, 34.3f, 270, 4.5f, 5, direction: 1), G("Проезд мимо места", 26, 34.3f, 270, 4.5f, 5, direction: 1),
                                G("Парковка задним ходом", 33.6f, 37.75f, 270, 3.3f, 8.6f, 2, -1, true, tolerance: 10), G("Выезд из места", 23.5f, 34.3f, 270, 4.5f, 5, direction: 1) },
                        new[] { G("Направо на север", 17.8f, 40, 0, 6, 5, direction: 1), G("Направо по северной дороге", 32, 44, 90, 6, 8, direction: 1),
                                G("Восточное кольцо на юг", 44, 18, 180, 6, 8, direction: 1) }),
                    L("slalom", "У5 · Змейка", "Направо в змейку, пройдите её без касаний, на выезде — направо.", 44, 14, 180,
                        new[] { G("Въезд в змейку", 38, 1, 270, 4.5f, 5, direction: 1), G("Изгиб", 31, -3, 180, 5, 5, direction: 1), G("Выезд", 25, -9.05f, 270, 4.5f, 5, direction: 1) },
                        new[] { G("Направо на север", 17.8f, -3, 0, 6, 6, direction: 1), G("Прямо через перекрёсток", 17.8f, 25, 0, 6, 6, direction: 1),
                                G("Налево на полосу разгона", 9, 47, 270, 6, 6, direction: 1) }),
                    L("shiftbrake", "У10 · Полоса разгона", "Разгонитесь, включите вторую передачу, затем остановитесь в рамке.", 9, 47, 270,
                        new[] { G("Вторая передача", -10, 47, 270, 4, 14, gear: 2, speed: 5, direction: 1), G("Торможение", -31, 47, 270, 4, 7, 2, whole: true) },
                        new[] { G("Западное кольцо на юг", -47, 41, 180, 6, 4, direction: 1) }),
                    L("railway", "У9 · Железнодорожный переезд", "Остановитесь перед стоп-линией, затем пересеките пути.", -47, 41, 180,
                        new[] { G("Остановка перед путями", -47, 38.9f, 180, 4, 5.6f, 2, whole: true), G("Переезд", -47, 25, 180, 5, 6, direction: 1) },
                        new[] { G("Западное кольцо на юг", -47, 0, 180, 6, 8, direction: 1), G("Южная дорога на восток", -10, -33.5f, 90, 6, 8, direction: 1),
                                G("Налево на север", 17.8f, -20, 0, 6, 6, direction: 1), G("Налево на запад", 5, 13.5f, 270, 6, 6, direction: 1) }),
                    L("90turns", "У4 · Повороты на 90°", "Направо в коридор, пройдите два поворота, на выезде — направо.", -8, 13.5f, 270,
                        new[] { G("Въезд в коридор", -21, 19, 0, 4.5f, 4, direction: 1), G("Первый поворот", -27, 30.7f, 270, 4.5f, 5, direction: 1),
                                G("Второй поворот", -32.5f, 36.5f, 0, 4.5f, 5, direction: 1) },
                        new[] { G("Направо по северной дороге", -15, 44, 90, 6, 8, direction: 1), G("Направо на юг", 14.8f, 30, 180, 6, 6, direction: 1),
                                G("Прямо через перекрёсток", 14.8f, -3, 180, 6, 6, direction: 1) }),
                    L("finish", "Финиш", "Прямо на юг через кольцо к стартовой площадке, остановитесь в рамке.", 14.8f, -25, 180,
                        new[] { G("Финиш", 14.8f, -37.3f, 180, 4.5f, 6.5f, 3, whole: true) }, none)
                }
            };
        }
    }
}
